export const POMODORO_BREAK_TIMER_SET_REQUEST =
  'POMODORO_BREAK_TIMER_SET_REQUEST';
export const POMODORO_BREAK_TIMER_SET_SUCCESS =
  'POMODORO_BREAK_TIMER_SET_SUCCESS';
export const POMODORO_BREAK_TIMER_SET_FAIL = 'POMODORO_BREAK_TIMER_SET_FAIL';

export const POMODORO_SESSION_TIMER_SET_REQUEST =
  'POMODORO_SESSION_TIMER_SET_REQUEST';
export const POMODORO_SESSION_TIMER_SET_SUCCESS =
  'POMODORO_SESSION_TIMER_SET_SUCCESS';
export const POMODORO_SESSION_TIMER_SET_FAIL =
  'POMODORO_SESSION_TIMER_SET_FAIL';
